#!/bin/bash

set -eux
set -o pipefail

DEPENDENCIES=("curl git")

check() {
  errcount=0
  for d in ${DEPENDENCIES[@]}; do
    if ! ( test $(which ${d}) )
    then
      echo "Please install ${d}"
      (( errcount++ ))
    fi
  done
  if [ $errcount -gt 0 ]; then
    exit 1
  fi
}

if ! ( test $(which brew) ); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.profile
  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

brew install neovim || echo "ignore exit code"
brew install tmux
brew install direnv
brew install zsh || echo "ignore exit code"
brew install fzf
brew install go
brew install docker

function copy_when_not_exist() {
  path=$1
  if [ ! -e ~/$path ]; then
    cp -a ./files/$path ~/$path
  fi
}

copy_when_not_exist .zshrc
copy_when_not_exist .config

if [ ! -e ~/.tmux.conf ]; then
  ln -s ~/.config/tmux/tmux.conf ~/.tmux.conf
fi
