#!/bin/bash

set -eux
set -o pipefail

DEPENDENCIES=("curl git")

check() {
  errcount=0
  for d in ${DEPENDENCIES[@]}; do
    if ! ( test $(which ${d}) )
    then
      echo "Please install ${d}"
      (( errcount++ ))
    fi
  done
  if [ $errcount -gt 0 ]; then
    exit 1
  fi
}

if ! ( test $(which brew) ) then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew install neovim
brew install tmux
brew install direnv
brew install zsh
brew install fzf
brew install go
