name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }} | base64 -d > key.json
          packer build -var google_project_id=${{ secrets.GOOGLE_PROJECT_ID }} -var google_application_credentials=key.json -var commit_hash=${{ github.sha }} packer.json
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t test .
  comment_test:
    runs-on: ubuntu-latest
    steps:
      - name: docker result
        run: docker run -it golang:1.19 echo "asd" >> $GITHUB_OUTPUT
      - name: comment-to-pr
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: $GITHUB_OUTPUT
